version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: danielkbernardi/nginx:prod
    container_name: nginx
    restart: unless-stopped
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    image: danielkbernardi/node:prod
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - nodenet
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge