version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: danielkbernardi/node:prod
    container_name: node
    networks:
      - nodenet

  nginx:
    build:
      context: ./../nginx
      dockerfile: Dockerfile.prod
    image: danielkbernardi/nginx:prod
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"

networks:
  nodenet:
    driver: bridge